name: 'pr-comment'
description: 'Adds PR changes as comment'
inputs:
  owner:
    description: 'The owner of repository (user or org)'
    required: true
  repo:
    description: 'The repository name'
    required: true
  pr_number:
    description: 'The number of PR'
    required: true
  token:
    description: 'The token to use to access GitHub API'
    required: true

runs:
  using: 'node16'
  main: 'dist/index.js'
